// Code generated by kanban/gen. DO NOT EDIT.

package banner

// Version ...
var Version = "v1.0.0"

// Copyright ...
var Copyright = "© 2020 - 2023 FloatTech"

// Banner ...
var Banner = "* OneBot + ZeroBot + Golang\n" +
	"* Version " + Version + " - 2023-08-02 01:22:12 +0800 CST\n" +
	"* Copyright " + Copyright + ". All Rights Reserved.\n" +
	"* Project: https://github.com/KomeiDiSanXian/BFHelper\n" +
	"* Origin Project: https://github.com/FloatTech/ZeroBot-Plugin"
